import { PhysicsPromptConfig } from '@/types/physics-engine';

export const AI_BEAUTIFICATION_BLACKLIST = [
  'beautiful',
  'flawless',
  'glowing',
  'artistic',
  'stylized',
  'perfect',
  'smooth skin',
  'airbrushed',
  'porcelain skin',
  'glamour',
  'hyperrealistic',
  'photorealistic',
  'unreal engine',
  'octane render',
  '8k',
  'cinematic lighting',
  'studio lighting',
  'rim light',
  'angelic',
  'glowing eyes',
  'digital art',
  'trending on artstation',
  'doll-like',
  'plastic',
  'filtered',
  'beautified',
  'dreamy',
  'soft glow',
  'fairytale'
];

export const PHYSICS_WHITELIST_TERMS = [
  'macro documentation',
  'dermatological detail',
  'unretouched raw capture',
  'inverse-square law light attenuation',
  'thermodynamic color temperature',
  'subsurface scattering IOR',
  'vellus hair rim interaction',
  'non-uniform specular sebum map',
  'subdermal capillary branching',
  'chromatic aberration on high-contrast edges',
  'chemical film grain',
  'micro-scratches and surface imperfections',
  'ambient occlusion corner grit',
  'gravitational equilibrium 9.8m/s²',
  'diegetic illumination source',
  'PBR non-zero surface roughness'
];

export const KELVIN_PRESETS = [
  { label: '1800K - ضوء شمعة / لهب (Candle Flame)', value: 1800, color: '#ff7700' },
  { label: '2700K - مصباح تنجستن دافئ (Tungsten Warm)', value: 2700, color: '#ffa442' },
  { label: '3200K - إضاءة هالوجين استوديو فيزيائي (Halogen)', value: 3200, color: '#ffc37a' },
  { label: '4500K - ضوء شمس الصباح الباكر (Early Morning Sun)', value: 4500, color: '#ffe4b5' },
  { label: '5600K - ضوء النهار المباشر المعياري (Daylight 5600K)', value: 5600, color: '#f8f8ff' },
  { label: '6500K - سماء غائمة نهاراً (Overcast Sky D65)', value: 6500, color: '#dbeafe' },
  { label: '8500K - سماء زرقاء عميقة في الظل (Deep Shade)', value: 8500, color: '#bfdbfe' },
  { label: '10000K - شفق أزرق قبل الشروق (Blue Hour Twilight)', value: 10000, color: '#93c5fd' },
];

export const IOR_TABLE = {
  skin: { label: 'بشرة الإنسان (Human Epidermis SSS)', value: 1.40 },
  water: { label: 'الماء العذب والسوائل (Fresh Water)', value: 1.333 },
  glass: { label: 'زجاج بصري خشن الأطراف (Optical Glass)', value: 1.52 },
  amber: { label: 'راتنج / عنبر (Resin / Amber)', value: 1.54 },
  vegetation: { label: 'طبقة شمع نباتية (Plant Cuticle Wax)', value: 1.48 },
  concrete: { label: 'خرسانة / صخور خشنة (Concrete & Rock)', value: 1.65 },
  custom: { label: 'قيمة فيزيائية مخصصة (Custom)', value: 1.45 },
};

export const SENSOR_FILM_PROFILES = [
  { id: 'arri_alexa_65', label: 'ARRI Alexa 65 (Large Format Cinema Sensor - Raw Log)', category: 'digital' },
  { id: 'red_vraptor_8k', label: 'RED V-Raptor 8K VV (High Dynamic Range - Sensor Raw)', category: 'digital' },
  { id: 'hasselblad_h6d', label: 'Hasselblad H6D-100c (Medium Format Forensic Clarity)', category: 'digital' },
  { id: 'kodak_portra_400', label: 'Kodak Portra 400 (Chemical 35mm C-41 Grain Structure)', category: 'film' },
  { id: 'ilford_hp5', label: 'Ilford HP5 Plus 400 (Monochrome Silver Halide Emulsion)', category: 'film' },
  { id: 'cinestill_800t', label: 'CineStill 800T (Tungsten Halation & Organic Grain)', category: 'film' },
  { id: 'fuji_pro400h', label: 'Fujifilm Pro 400H (Subtle Cool Shadows & Organic Grain)', category: 'film' },
];

export const DEFAULT_CONFIG: PhysicsPromptConfig = {
  userIdea: 'لقطة توثيقية مقربة لوجه حداد مسن في ورشته، مع قطرات عرق وتطاير ذرات الغبار تحت ضوء نافذة شمالية',
  language: 'ar',
  targetEngine: 'universal',
  intensity: 'forensic',
  optics: {
    kelvin: 3200,
    lightDistanceMeters: 1.8,
    inverseSquareLawStrict: true,
    diegeticSource: 'Single 3200K low-hung tungsten workshop bulb & natural 5600K slit window light',
    volumetricDensity: 0.35,
    volumetricType: 'dust_motes',
    colorBleedAmount: 0.4,
  },
  camera: {
    aperture: 'f/2.8',
    shutterSpeed: '1/125s',
    iso: 800,
    sensorOrFilm: 'ARRI Alexa 65',
    lensFocalLength: '85mm portrait prime',
    chromaticAberration: true,
    barrelDistortion: true,
    filmGrainOptical: true,
  },
  materials: {
    roughness: 0.42,
    metalness: 0.05,
    ior: 1.40,
    iorPreset: 'skin',
    ambientTempCelsius: 31,
    thermalEffect: 'sweat_micro_droplets',
  },
  mechanics: {
    gravityConstant: 9.8,
    centerOfMassEnforced: true,
    fabricSagAndTension: true,
    fluidDynamics: 'surface_tension_droplet',
  },
  biology: {
    includeLivingSubject: true,
    vellusHair: true,
    nonUniformSebum: true,
    capillaryMapping: true,
    irregularPores: true,
    microAsymmetry: true,
  },
  entropy: {
    temporalWear: 'heavy_weathering',
    uvDegradation: true,
    oxidationRust: true,
    ambientOcclusionDirt: true,
  },
  lexical: {
    autoScrubBlacklist: true,
    autoInjectWhitelist: true,
    customBlacklist: [],
    customWhitelist: [],
  },
};

export interface PromptPreset {
  id: string;
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  iconName: string;
  config: Partial<PhysicsPromptConfig>;
}

export const PRESET_SCENARIOS: PromptPreset[] = [
  {
    id: 'forensic_blacksmith',
    titleAr: 'حداد مسن في ورشة حديد (Forensic Portrait)',
    titleEn: 'Elderly Blacksmith in Metal Workshop',
    descriptionAr: 'توثيق بشري عالي الواقعية: زغب الخوخ، لمعان دهني غير متساوٍ، عرق، صدأ، إضاءة مبررة فيزيائياً.',
    descriptionEn: 'High biological fidelity: vellus hair, non-uniform sebum, sweat, rust, diegetic tungsten light.',
    iconName: 'Flame',
    config: {
      userIdea: 'A documentary macro portrait of an 68-year-old seasoned blacksmith inside a dimly lit iron forge, soot-stained wrinkled skin, metal shavings on apron',
      intensity: 'forensic',
      optics: {
        kelvin: 2800,
        lightDistanceMeters: 1.2,
        inverseSquareLawStrict: true,
        diegeticSource: 'Glowing ember forge bed (2200K) + low hanging bare incandescent bulb (2800K)',
        volumetricDensity: 0.45,
        volumetricType: 'dust_motes',
        colorBleedAmount: 0.5,
      },
      camera: {
        aperture: 'f/2.8',
        shutterSpeed: '1/125s',
        iso: 800,
        sensorOrFilm: 'ARRI Alexa 65',
        lensFocalLength: '85mm portrait prime',
        chromaticAberration: true,
        barrelDistortion: true,
        filmGrainOptical: true,
      },
      materials: {
        roughness: 0.48,
        metalness: 0.15,
        ior: 1.40,
        iorPreset: 'skin',
        ambientTempCelsius: 34,
        thermalEffect: 'sweat_micro_droplets',
      },
      biology: {
        includeLivingSubject: true,
        vellusHair: true,
        nonUniformSebum: true,
        capillaryMapping: true,
        irregularPores: true,
        microAsymmetry: true,
      },
      entropy: {
        temporalWear: 'heavy_weathering',
        uvDegradation: false,
        oxidationRust: true,
        ambientOcclusionDirt: true,
      },
    },
  },
  {
    id: 'fluid_mechanics_splash',
    titleAr: 'ديناميكا الموائع والتوتر السطحي (Fluid Mechanics)',
    titleEn: 'Fluid Surface Tension & Droplet Splash',
    descriptionAr: 'قطرة ماء ترتطم بسطح سائل مع حساب التوتر السطحي وقوة الجاذبية 9.8 م/ث² وانكسار الضوء IOR 1.333.',
    descriptionEn: 'Water droplet kinetic impact, surface tension Rayleigh breakup, gravity vector 9.8m/s², IOR 1.333 refraction.',
    iconName: 'Droplets',
    config: {
      userIdea: 'High-speed capture of a single water droplet colliding with a calm puddle on rough slate stone, forming a coronet splash with micro-satellite beads',
      intensity: 'extreme_optical',
      optics: {
        kelvin: 5600,
        lightDistanceMeters: 0.8,
        inverseSquareLawStrict: true,
        diegeticSource: 'Direct 5600K Xenon strobe flash bounced off white card at 45 degree angle',
        volumetricDensity: 0.05,
        volumetricType: 'sea_spray',
        colorBleedAmount: 0.2,
      },
      camera: {
        aperture: 'f/8',
        shutterSpeed: '1/8000s',
        iso: 400,
        sensorOrFilm: 'Hasselblad H6D-100c',
        lensFocalLength: '100mm macro',
        chromaticAberration: true,
        barrelDistortion: false,
        filmGrainOptical: false,
      },
      materials: {
        roughness: 0.12,
        metalness: 0.0,
        ior: 1.333,
        iorPreset: 'water',
        ambientTempCelsius: 18,
        thermalEffect: 'none',
      },
      mechanics: {
        gravityConstant: 9.8,
        centerOfMassEnforced: true,
        fabricSagAndTension: false,
        fluidDynamics: 'water_splash_momentum',
      },
      biology: {
        includeLivingSubject: false,
        vellusHair: false,
        nonUniformSebum: false,
        capillaryMapping: false,
        irregularPores: false,
        microAsymmetry: false,
      },
      entropy: {
        temporalWear: 'moderate_wear',
        uvDegradation: false,
        oxidationRust: false,
        ambientOcclusionDirt: true,
      },
    },
  },
  {
    id: 'wet_asphalt_night',
    titleAr: 'إسفلت مبلل وإضاءة صوديوم ليلية (Wet Asphalt Urban)',
    titleEn: 'Wet Asphalt & 1800K Sodium Vapor Streetlight',
    descriptionAr: 'قانون التربيع العكسي للضوء، انعكاسات مبررة فيزيائياً، ضباب رطب وتآكل أسطح خرسانية.',
    descriptionEn: 'Inverse-square attenuation, diegetic 1800K low-pressure sodium vapor lamp, Schlieren mist, rough asphalt PBR.',
    iconName: 'CloudRain',
    config: {
      userIdea: 'Empty urban alleyway at 2:30 AM after torrential downpour, cracked asphalt pavement with shallow puddles reflecting a humming yellow sodium streetlight',
      intensity: 'cinematic',
      optics: {
        kelvin: 1900,
        lightDistanceMeters: 4.5,
        inverseSquareLawStrict: true,
        diegeticSource: 'Single buzzing low-pressure sodium vapor street lamp overhead at 5 meters height',
        volumetricDensity: 0.6,
        volumetricType: 'morning_mist',
        colorBleedAmount: 0.7,
      },
      camera: {
        aperture: 'f/1.8',
        shutterSpeed: '1/30s',
        iso: 1600,
        sensorOrFilm: 'CineStill 800T',
        lensFocalLength: '35mm prime',
        chromaticAberration: true,
        barrelDistortion: true,
        filmGrainOptical: true,
      },
      materials: {
        roughness: 0.65,
        metalness: 0.08,
        ior: 1.333,
        iorPreset: 'water',
        ambientTempCelsius: 11,
        thermalEffect: 'condensation_frost',
      },
      mechanics: {
        gravityConstant: 9.8,
        centerOfMassEnforced: true,
        fabricSagAndTension: false,
        fluidDynamics: 'surface_tension_droplet',
      },
      biology: {
        includeLivingSubject: false,
        vellusHair: false,
        nonUniformSebum: false,
        capillaryMapping: false,
        irregularPores: false,
        microAsymmetry: true,
      },
      entropy: {
        temporalWear: 'heavy_weathering',
        uvDegradation: true,
        oxidationRust: true,
        ambientOcclusionDirt: true,
      },
    },
  },
  {
    id: 'macro_entomology',
    titleAr: 'ماكرو بصري دقيق لعالم الحشرات (Macro Entomology)',
    titleEn: 'Extreme Optical Macro of Insect Exoskeleton',
    descriptionAr: 'انكسار الكيتين، عيون مركبة غير متماثلة بدقة مجهرية، تشوه لوني على حواف العدسة.',
    descriptionEn: 'Chitin refractive index, micro-scratches on iridescent carapace, high-magnification optical chromatic aberration.',
    iconName: 'Bug',
    config: {
      userIdea: 'Extreme macro photographic study of a scarred emerald jewel beetle carapace resting on damp decaying tree bark, showing compound eye facet irregularity',
      intensity: 'extreme_optical',
      optics: {
        kelvin: 6500,
        lightDistanceMeters: 0.3,
        inverseSquareLawStrict: true,
        diegeticSource: 'Overcast ambient sky light through dense canopy leaves at 11 AM',
        volumetricDensity: 0.1,
        volumetricType: 'dust_motes',
        colorBleedAmount: 0.3,
      },
      camera: {
        aperture: 'f/11',
        shutterSpeed: '1/200s',
        iso: 200,
        sensorOrFilm: 'Hasselblad H6D-100c',
        lensFocalLength: '100mm macro',
        chromaticAberration: true,
        barrelDistortion: false,
        filmGrainOptical: false,
      },
      materials: {
        roughness: 0.18,
        metalness: 0.85,
        ior: 1.54,
        iorPreset: 'amber',
        ambientTempCelsius: 22,
        thermalEffect: 'condensation_frost',
      },
      biology: {
        includeLivingSubject: true,
        vellusHair: false,
        nonUniformSebum: false,
        capillaryMapping: false,
        irregularPores: true,
        microAsymmetry: true,
      },
      entropy: {
        temporalWear: 'moderate_wear',
        uvDegradation: false,
        oxidationRust: false,
        ambientOcclusionDirt: true,
      },
    },
  },
  {
    id: 'ancient_architectural_decay',
    titleAr: 'إنتروبيا معمارية وخرسانة متآكلة (Architectural Entropy)',
    titleEn: 'Decaying Brutalist Concrete & Rust Patina',
    descriptionAr: 'تأثير الأشعة فوق البنفسجية UV، تآكل حديد التسليح، غبار عميق في زوايا الظل المحيطي (Ambient Occlusion).',
    descriptionEn: 'UV solar bleaching, rebar rust streaking, structural center of gravity load bearing, deep crevice occlusion dust.',
    iconName: 'Building2',
    config: {
      userIdea: 'Brutalist abandoned concrete research observatory on an exposed coastal cliff, spalling concrete revealing corroded rebar, saltwater patina',
      intensity: 'forensic',
      optics: {
        kelvin: 5800,
        lightDistanceMeters: 15.0,
        inverseSquareLawStrict: true,
        diegeticSource: 'Direct harsh afternoon coastal sun with salt haze diffusion + marine horizon bounce',
        volumetricDensity: 0.4,
        volumetricType: 'sea_spray',
        colorBleedAmount: 0.45,
      },
      camera: {
        aperture: 'f/8',
        shutterSpeed: '1/500s',
        iso: 100,
        sensorOrFilm: 'RED V-Raptor 8K VV',
        lensFocalLength: '24mm wide-angle',
        chromaticAberration: true,
        barrelDistortion: true,
        filmGrainOptical: true,
      },
      materials: {
        roughness: 0.88,
        metalness: 0.22,
        ior: 1.65,
        iorPreset: 'concrete',
        ambientTempCelsius: 16,
        thermalEffect: 'condensation_frost',
      },
      mechanics: {
        gravityConstant: 9.8,
        centerOfMassEnforced: true,
        fabricSagAndTension: false,
        fluidDynamics: 'none',
      },
      biology: {
        includeLivingSubject: false,
        vellusHair: false,
        nonUniformSebum: false,
        capillaryMapping: false,
        irregularPores: false,
        microAsymmetry: true,
      },
      entropy: {
        temporalWear: 'ancient_decay',
        uvDegradation: true,
        oxidationRust: true,
        ambientOcclusionDirt: true,
      },
    },
  },
];
