import {
  LocationCategory,
  LocationItem,
  SceneType,
  PoseType,
  LightingSource,
  TimeOfDay,
  WeatherCondition,
  BackgroundActivityLevel,
  SelfieSceneState,
} from '@/types/selfie-engine';

export const SCENE_TYPE_DEFINITIONS: Record<
  SceneType,
  { nameAr: string; nameEn: string; allowedCategories: LocationCategory[] }
> = {
  front_selfie: {
    nameAr: 'سيلفي أمامي كلاسيكي (Front Selfie)',
    nameEn: 'Front Handheld Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'parking_areas', 'shopping', 'airport', 'desert_roadtrips', 'mountain_locations', 'farms_palms'],
  },
  standing_selfie: {
    nameAr: 'سيلفي وقوف (Standing Selfie)',
    nameEn: 'Standing Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'parking_areas', 'gas_stations', 'public_buildings', 'shopping', 'airport', 'desert_roadtrips', 'mountain_locations', 'farms_palms', 'gym_fitness'],
  },
  walking_selfie: {
    nameAr: 'سيلفي أثناء المشي (Walking Selfie)',
    nameEn: 'Walking Selfie (Mid-Stride)',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'shopping', 'airport', 'public_buildings', 'farms_palms'],
  },
  seated_selfie: {
    nameAr: 'سيلفي جلوس (Seated Selfie)',
    nameEn: 'Seated Selfie',
    allowedCategories: ['restaurants_cafes', 'office_work', 'car_interior', 'airport', 'mountain_locations', 'public_buildings', 'gym_fitness'],
  },
  outdoor_selfie: {
    nameAr: 'سيلفي خارجي عام (Outdoor Selfie)',
    nameEn: 'Outdoor Environmental Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'parking_areas', 'gas_stations', 'desert_roadtrips', 'mountain_locations', 'farms_palms'],
  },
  mirror_selfie: {
    nameAr: 'سيلفي مرآة (Mirror Selfie)',
    nameEn: 'Mirror Selfie',
    allowedCategories: ['gym_fitness', 'public_buildings', 'wash_mirrors'],
  },
  inside_car_driver_selfie: {
    nameAr: 'سيلفي مقعد السائق (Inside Car Driver)',
    nameEn: 'Inside Car Driver Seat',
    allowedCategories: ['car_interior'],
  },
  inside_car_passenger_selfie: {
    nameAr: 'سيلفي مقعد الراكب (Inside Car Passenger)',
    nameEn: 'Inside Car Passenger Seat',
    allowedCategories: ['car_interior'],
  },
  car_adjacent_selfie: {
    nameAr: 'سيلفي بجوار السيارة (Beside Car)',
    nameEn: 'Car Adjacent Selfie',
    allowedCategories: ['car_exterior', 'parking_areas', 'gas_stations', 'desert_roadtrips', 'mountain_locations'],
  },
  close_face_selfie: {
    nameAr: 'سيلفي مقرب للوجه (Close Face Selfie)',
    nameEn: 'Close Face Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'car_interior', 'restaurants_cafes', 'office_work', 'gym_fitness'],
  },
  wide_environmental_selfie: {
    nameAr: 'سيلفي بيئي واسع (Wide Environmental)',
    nameEn: 'Wide Environmental Selfie',
    allowedCategories: ['waterfront_corniche', 'shopping', 'airport', 'desert_roadtrips', 'mountain_locations', 'farms_palms', 'parking_areas'],
  },
  high_angle_selfie: {
    nameAr: 'سيلفي بزاوية مرتفعة (High Angle)',
    nameEn: 'High Angle Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'restaurants_cafes', 'office_work', 'gym_fitness', 'public_buildings'],
  },
  low_angle_selfie: {
    nameAr: 'سيلفي بزاوية منخفضة (Low Angle)',
    nameEn: 'Low Angle Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'parking_areas', 'desert_roadtrips', 'mountain_locations'],
  },
  three_quarter_selfie: {
    nameAr: 'سيلفي بزاوية ثلاثة أرباع (Three-Quarter)',
    nameEn: 'Three-Quarter Selfie',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'car_exterior', 'restaurants_cafes', 'office_work', 'gym_fitness'],
  },
  leaning_selfie: {
    nameAr: 'سيلفي مستند على سطح (Leaning Selfie)',
    nameEn: 'Leaning Against Surface',
    allowedCategories: ['city_streets', 'waterfront_corniche', 'car_exterior', 'parking_areas', 'gas_stations', 'public_buildings', 'desert_roadtrips', 'mountain_locations'],
  },
  street_night_selfie: {
    nameAr: 'سيلفي شارع ليلي (Street Night)',
    nameEn: 'Street Night Selfie',
    allowedCategories: ['city_streets'],
  },
  parking_night_selfie: {
    nameAr: 'سيلفي مواقف ليلية (Parking Night)',
    nameEn: 'Parking Night Selfie',
    allowedCategories: ['parking_areas'],
  },
  gas_station_selfie: {
    nameAr: 'سيلفي محطة وقود (Gas Station)',
    nameEn: 'Gas Station Selfie',
    allowedCategories: ['gas_stations'],
  },
  restaurant_table_selfie: {
    nameAr: 'سيلفي طاولة مطعم/مقهى (Restaurant Table)',
    nameEn: 'Restaurant / Cafe Table',
    allowedCategories: ['restaurants_cafes'],
  },
  desk_work_selfie: {
    nameAr: 'سيلفي مكتب عمل (Desk Work)',
    nameEn: 'Desk Workstation Selfie',
    allowedCategories: ['office_work'],
  },
  gym_workout_selfie: {
    nameAr: 'سيلفي تمرين رياضي (Gym Workout)',
    nameEn: 'Gym Workout Selfie',
    allowedCategories: ['gym_fitness'],
  },
  post_workout_selfie: {
    nameAr: 'سيلفي بعد التمرين الرياضي (Post Workout)',
    nameEn: 'Post-Workout Physical Selfie',
    allowedCategories: ['gym_fitness'],
  },
  beach_corniche_selfie: {
    nameAr: 'سيلفي كورنيش/واجهة بحرية (Corniche Selfie)',
    nameEn: 'Waterfront Corniche Selfie',
    allowedCategories: ['waterfront_corniche'],
  },
  desert_stop_selfie: {
    nameAr: 'سيلفي استراحة صحراوية (Desert Road Stop)',
    nameEn: 'Desert Road Trip Selfie',
    allowedCategories: ['desert_roadtrips'],
  },
  farm_palm_selfie: {
    nameAr: 'سيلفي مزرعة نخيل (Palm Farm Selfie)',
    nameEn: 'Palm Farm / Rural Selfie',
    allowedCategories: ['farms_palms'],
  },
  mountain_view_selfie: {
    nameAr: 'سيلفي إطلالة جبلية (Mountain View Selfie)',
    nameEn: 'Mountain Viewpoint Selfie',
    allowedCategories: ['mountain_locations'],
  },
};

export const LOCATION_CATEGORIES: { id: LocationCategory; nameAr: string; nameEn: string }[] = [
  { id: 'city_streets', nameAr: 'شوارع وأحياء المدينة', nameEn: 'City & Streets' },
  { id: 'waterfront_corniche', nameAr: 'الكورنيش والواجهات البحرية', nameEn: 'Waterfront & Corniche' },
  { id: 'car_interior', nameAr: 'داخل السيارة (متوقفة)', nameEn: 'Inside Car (Parked)' },
  { id: 'car_exterior', nameAr: 'بجوار السيارة', nameEn: 'Beside Car' },
  { id: 'parking_areas', nameAr: 'المواقف والساحات', nameEn: 'Parking Areas' },
  { id: 'gas_stations', nameAr: 'محطات الوقود', nameEn: 'Gas Stations' },
  { id: 'restaurants_cafes', nameAr: 'المطاعم والمقاهي', nameEn: 'Restaurants & Cafes' },
  { id: 'office_work', nameAr: 'المكتب وبيئة العمل', nameEn: 'Office & Work' },
  { id: 'gym_fitness', nameAr: 'النادي الرياضي والتمارين', nameEn: 'Gym & Fitness' },
  { id: 'public_buildings', nameAr: 'المباني العامة والممرات', nameEn: 'Public Buildings' },
  { id: 'wash_mirrors', nameAr: 'مغاسل ومرايا عامة', nameEn: 'Public Wash & Mirrors' },
  { id: 'shopping', nameAr: 'المتاجر والأسواق والمولات', nameEn: 'Shopping & Supermarket' },
  { id: 'airport', nameAr: 'صالة المطار وبوابات السفر', nameEn: 'Airport Terminal' },
  { id: 'desert_roadtrips', nameAr: 'طرق واستراحات الصحراء', nameEn: 'Desert & Road Trips' },
  { id: 'mountain_locations', nameAr: 'المرتفعات والإطلالات الجبلية', nameEn: 'Mountain Locations' },
  { id: 'farms_palms', nameAr: 'مزارع النخيل والريف', nameEn: 'Farms & Palm Areas' },
];

export const LOCATIONS_DATABASE: LocationItem[] = [
  // City Streets
  {
    id: 'residential_street',
    nameAr: 'شارع سكني هادئ',
    nameEn: 'Residential Street',
    category: 'city_streets',
    descriptionAr: 'رصيف شارع سكني مع جدران فلل، سيارات متوقفة، أسفلت عادي مع غبار شوارع خفيف.',
    descriptionEn: 'Paved sidewalk alongside residential boundary walls, parked daily vehicles, utility meters, subtle road dust.',
    compatibleSceneTypes: ['standing_selfie', 'walking_selfie', 'outdoor_selfie', 'front_selfie', 'leaning_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['direct_sun', 'open_shade', 'golden_hour', 'street_led_poles'],
    defaultActivity: 'sparse',
    environmentalElements: ['asphalt road', 'concrete curbs', 'parked sedan', 'residential boundary wall', 'utility covers'],
    saudiDetails: ['yellow and black curb paint accents', 'desert dust patina on parked cars', 'residential air conditioning units on exterior wall'],
  },
  {
    id: 'commercial_street',
    nameAr: 'شارع تجاري نشط',
    nameEn: 'Commercial Urban Street',
    category: 'city_streets',
    descriptionAr: 'واجهات محلات تجارية حقيقية، أرصفة مشاة، سيارات متوقفة بميلان، ولوحات إرشادية.',
    descriptionEn: 'Active commercial storefront sidewalk, parked cars, pedestrian traffic, utility poles and Arabic signage spill.',
    compatibleSceneTypes: ['standing_selfie', 'walking_selfie', 'outdoor_selfie', 'street_night_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['direct_sun', 'open_shade', 'golden_hour', 'street_led_poles', 'storefront_light_spill'],
    defaultActivity: 'moderate',
    environmentalElements: ['commercial sidewalk', 'retail storefronts', 'streetlights', 'parked SUVs', 'pedestrians in background'],
    saudiDetails: ['bilingual Arabic storefront signs', 'standard Saudi municipal garbage bins', 'faded pedestrian crosswalk markings'],
  },
  {
    id: 'business_district',
    nameAr: 'حي الأعمال والأبراج المكتبية',
    nameEn: 'Business District Sidewalk',
    category: 'city_streets',
    descriptionAr: 'رصيف خرساني واسع أمام مبنى زجاجي تجاري، أشجار نخيل بلدية، حركة موظفين خفيفة.',
    descriptionEn: 'Wide modern corporate pavement, reflective building exterior, municipal palm planters, discreet pedestrian activity.',
    compatibleSceneTypes: ['standing_selfie', 'walking_selfie', 'front_selfie', 'leaning_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['open_shade', 'golden_hour', 'street_led_poles'],
    defaultActivity: 'light',
    environmentalElements: ['granite pavers', 'corporate glass facade', 'metal bollards', 'distant commuters'],
    saudiDetails: ['neatly trimmed date palms', 'modern Saudi financial center architectural proportions'],
  },
  {
    id: 'night_street',
    nameAr: 'شارع حضري ليلي',
    nameEn: 'Night Urban Street',
    category: 'city_streets',
    descriptionAr: 'شارع ليلي واقعي مضاء بأعمدة LED بلدية مع تسرب إضاءة اللوحات، وأسفلت جاف عاكس جزئياً.',
    descriptionEn: 'Ordinary nocturnal street with overhead LED pole illumination, storefront spill, parked cars casting grounded shadows.',
    compatibleSceneTypes: ['street_night_selfie', 'standing_selfie', 'front_selfie', 'leaning_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['street_led_poles', 'storefront_light_spill'],
    defaultActivity: 'light',
    environmentalElements: ['dark asphalt', 'lit streetlight poles', 'closed storefront shutters', 'parked vehicles in shadow'],
    saudiDetails: ['warm sodium and cool LED mixed urban lighting', 'distant neon Arabic signs'],
  },

  // Waterfront & Corniche
  {
    id: 'jeddah_corniche',
    nameAr: 'كورنيش جدة الواجهة البحرية',
    nameEn: 'Jeddah Waterfront Corniche',
    category: 'waterfront_corniche',
    descriptionAr: 'ممشى الكورنيش مع درابزين الحماية، أفق البحر الممتد، رطوبة ساحلية خفيفة، وأعمدة إنارة.',
    descriptionEn: 'Coastal promenade pavers, safety railing, Red Sea horizon with natural humidity haze, distant light pedestrians.',
    compatibleSceneTypes: ['beach_corniche_selfie', 'standing_selfie', 'walking_selfie', 'leaning_selfie', 'wide_environmental_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Railing!
    allowedLighting: ['direct_sun', 'harsh_noon', 'golden_hour', 'street_led_poles'],
    defaultActivity: 'light',
    environmentalElements: ['seaside promenade railing', 'open sea horizon', 'public benches', 'distant lampposts'],
    saudiDetails: ['Red Sea coastal humidity haze', 'authentic Jeddah corniche concrete pavers and stainless steel railing'],
  },
  {
    id: 'khobar_corniche',
    nameAr: 'كورنيش الخبر الواجهة البحرية',
    nameEn: 'Khobar Waterfront Corniche',
    category: 'waterfront_corniche',
    descriptionAr: 'مسار المشاة بمحاذاة الخليج العربي، مسطحات عشبية جانبية، إنارة ساحلية، وأفق بحري هادئ.',
    descriptionEn: 'Arabian Gulf waterfront walkway, neat grass verge, modern public lights, calm sea horizon with subtle maritime mist.',
    compatibleSceneTypes: ['beach_corniche_selfie', 'standing_selfie', 'walking_selfie', 'leaning_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['direct_sun', 'golden_hour', 'overcast_diffused', 'street_led_poles'],
    defaultActivity: 'light',
    environmentalElements: ['granite seaside walkway', 'coastal metal barriers', 'distant water tower or Gulf horizon'],
    saudiDetails: ['Khobar seaside promenade architecture', 'ambient Gulf breeze interacting with loose fabric'],
  },
  {
    id: 'coastal_parking',
    nameAr: 'مواقف سيارات الواجهة البحرية',
    nameEn: 'Coastal Promenade Parking Area',
    category: 'waterfront_corniche',
    descriptionAr: 'مواقف سيارات مفتوحة مطلة على البحر، رصيف فاصل، نسيم بحري، وسيارات متوقفة بانتظام.',
    descriptionEn: 'Open asphalt coastal parking lot, concrete tire stops, sea visible beyond sidewalk barrier.',
    compatibleSceneTypes: ['standing_selfie', 'car_adjacent_selfie', 'leaning_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface', 'beside_car_open_door_clearance'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Car body
    allowedLighting: ['direct_sun', 'golden_hour', 'street_led_poles'],
    defaultActivity: 'sparse',
    environmentalElements: ['asphalt parking spots', 'concrete wheel stops', 'parked vehicle', 'sea background'],
    saudiDetails: ['Gulf-spec tinted car windows', 'fine coastal salt haze'],
  },

  // Car Environments (Inside Car)
  {
    id: 'car_driver_seat',
    nameAr: 'مقعد السائق (السيارة متوقفة تماماً)',
    nameEn: 'Stationary Car Driver Seat',
    category: 'car_interior',
    descriptionAr: 'داخل مقصورة السيارة متوقفة، زاوية المقود، حزام الأمان، انعكاسات الزجاج الطبيعية ومسند الرأس.',
    descriptionEn: 'Interior driver cockpit, steering wheel rim, headrest compression, authentic window perspective, phone within natural arm span.',
    compatibleSceneTypes: ['inside_car_driver_selfie', 'seated_selfie', 'close_face_selfie'],
    allowedPoses: ['inside_car_driver_one_hand_wheel', 'seated_cushion_compression'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Seat
    allowedLighting: ['open_shade', 'golden_hour', 'car_interior_dome_light_dim', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['steering wheel', 'dashboard textured plastic', 'seatbelt across shoulder', 'side mirror view in window'],
    saudiDetails: ['parking brake engaged', 'subtle Saudi sun visor positioning', 'dashboard phone mount silhouette'],
  },
  {
    id: 'car_passenger_seat',
    nameAr: 'مقعد الراكب الأمامي',
    nameEn: 'Stationary Car Passenger Seat',
    category: 'car_interior',
    descriptionAr: 'مقعد الراكب، مسند الذراع الأوسط، زجاج الباب الجانبي، وراحة طبيعية داخل المقصورة.',
    descriptionEn: 'Front passenger seat cabin perspective, center console armrest, side window daylight falloff.',
    compatibleSceneTypes: ['inside_car_passenger_selfie', 'seated_selfie', 'close_face_selfie'],
    allowedPoses: ['inside_car_passenger_armrest', 'seated_cushion_compression'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['open_shade', 'golden_hour', 'car_interior_dome_light_dim'],
    defaultActivity: 'sparse',
    environmentalElements: ['glove compartment area', 'passenger headrest', 'door trim panel', 'side window frame'],
    saudiDetails: ['light ceramic window tint gradient', 'tissue box on center console'],
  },

  // Car Environments (Beside Car)
  {
    id: 'beside_parked_car',
    nameAr: 'بجوار السيارة المتوقفة (خارج السيارة)',
    nameEn: 'Standing Beside Parked Vehicle',
    category: 'car_exterior',
    descriptionAr: 'وقوف بجانب باب السيارة الخارجي، انعكاس ضوء طبيعي على هيكل السيارة المعدني.',
    descriptionEn: 'Standing adjacent to parked vehicle, correct scale between human height and roofline, realistic panel reflections.',
    compatibleSceneTypes: ['car_adjacent_selfie', 'standing_selfie', 'leaning_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface', 'beside_car_open_door_clearance'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Vehicle body
    allowedLighting: ['direct_sun', 'open_shade', 'golden_hour', 'parking_led_canopy'],
    defaultActivity: 'sparse',
    environmentalElements: ['parked car door and side mirror', 'ground asphalt', 'vehicle door handle', 'shadow cast on ground'],
    saudiDetails: ['Gulf-spec SUV or sedan model', 'clean metallic or pearl white paint with natural environmental dust'],
  },

  // Parking Areas
  {
    id: 'mall_parking_outdoor',
    nameAr: 'مواقف المول الخارجية',
    nameEn: 'Outdoor Mall Parking Lot',
    category: 'parking_areas',
    descriptionAr: 'ساحة مواقف خارجية مع أعمدة إنارة ومسارات تخطيط أرضية، وسيارات متوقفة في الخلفية.',
    descriptionEn: 'Commercial outdoor parking bays, yellow painted stall lines, light pole fixtures, distant shoppers.',
    compatibleSceneTypes: ['standing_selfie', 'car_adjacent_selfie', 'leaning_selfie', 'parking_night_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['direct_sun', 'open_shade', 'golden_hour', 'parking_led_canopy', 'street_led_poles'],
    defaultActivity: 'light',
    environmentalElements: ['painted parking lines', 'tall lighting poles', 'parked cars at varying angles', 'distant mall facade entrance'],
    saudiDetails: ['typical Saudi shade canopy structures in sections', 'Toyota/Nissan daily commuter vehicles in background'],
  },
  {
    id: 'parking_covered_night',
    nameAr: 'مواقف مغطاة ليلية',
    nameEn: 'Night Covered Structure Parking',
    category: 'parking_areas',
    descriptionAr: 'مواقف مغطاة بأعمدة خرسانية وإنارة سقفية عملية، وظلال واضحة على الأرضية الملساء.',
    descriptionEn: 'Covered concrete garage bays, overhead industrial fluorescent/LED fixtures, concrete pillars with warning stripes.',
    compatibleSceneTypes: ['parking_night_selfie', 'standing_selfie', 'car_adjacent_selfie', 'leaning_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['parking_led_canopy', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['overhead light fixtures', 'concrete support column', 'epoxy or concrete floor with tire marks'],
    saudiDetails: ['Saudi directional exit signs in Arabic and English', 'clean municipal basement or shaded bay layout'],
  },

  // Gas Stations
  {
    id: 'gas_station_bay',
    nameAr: 'محطة وقود نموذجية',
    nameEn: 'Standard Highway / City Gas Station',
    category: 'gas_stations',
    descriptionAr: 'تحت مظلة المحطة، مضخات الوقود، أرضية خرسانية، متجر تموينات في الخلفية، وإنارة المظلة القوية.',
    descriptionEn: 'Gas station service island, fuel dispenser pumps, overhead canopy downlights, convenience store glass front in background.',
    compatibleSceneTypes: ['gas_station_selfie', 'standing_selfie', 'car_adjacent_selfie', 'leaning_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'beside_car_open_door_clearance', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['gas_station_canopy_fixtures', 'storefront_light_spill'],
    defaultActivity: 'light',
    environmentalElements: ['fuel pump dispenser', 'overhead high-bay LED canopy', 'safety bollards', 'convenience store facade'],
    saudiDetails: ['Saudi branded fuel station aesthetics (Sasco, Aldrees, Enoc)', 'Arabic pricing LED boards in distance'],
  },

  // Restaurants & Cafes
  {
    id: 'specialty_coffee_table',
    nameAr: 'طاولة مقهى مختص',
    nameEn: 'Specialty Coffee Shop Table',
    category: 'restaurants_cafes',
    descriptionAr: 'طاولة خشبية متصلة وثابتة، كوب قهوة مرتكز فعلياً، إضاءة عملية دافئة، وكراسي مريحة.',
    descriptionEn: 'Specialty cafe interior, solid wooden table surface, ceramic cup resting with physical contact, warm practical ambient light.',
    compatibleSceneTypes: ['restaurant_table_selfie', 'seated_selfie', 'close_face_selfie', 'three_quarter_selfie'],
    allowedPoses: ['seated_table_casual', 'holding_cup_table', 'seated_cushion_compression'],
    hasMirror: false,
    hasCar: false,
    hasTable: true,
    hasDesk: false,
    hasContactSurface: true, // Table and chair
    allowedLighting: ['cafe_warm_practical_amber', 'open_shade', 'mixed_practical_ambient'],
    defaultActivity: 'light',
    environmentalElements: ['wooden or terrazzo table', 'ceramic flat white cup', 'paper napkin', 'cushioned dining chair'],
    saudiDetails: ['contemporary Saudi specialty cafe interior architecture', 'discreet local patron seating in soft-focus background'],
  },
  {
    id: 'outdoor_cafe_patio',
    nameAr: 'جلسة خارجية بمقهى',
    nameEn: 'Outdoor Cafe Patio Seating',
    category: 'restaurants_cafes',
    descriptionAr: 'طاولة خارجية على رصيف مشاة مبلط، مظلة قماشية، إضاءة طبيعية، وأجواء شمسية مريحة.',
    descriptionEn: 'Outdoor patio cafe table, fabric umbrella shade, open daylight falloff, paved walkway background.',
    compatibleSceneTypes: ['restaurant_table_selfie', 'seated_selfie', 'outdoor_selfie'],
    allowedPoses: ['seated_table_casual', 'holding_cup_table'],
    hasMirror: false,
    hasCar: false,
    hasTable: true,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['open_shade', 'golden_hour', 'direct_sun'],
    defaultActivity: 'light',
    environmentalElements: ['outdoor metal/wood table', 'drinking glass or bottle', 'shaded patio canopy', 'potted plant planter'],
    saudiDetails: ['patio mist cooling nozzles overhead', 'decorative Arabic ceramic floor tile accents'],
  },

  // Office & Work
  {
    id: 'office_workstation_desk',
    nameAr: 'مكتب عمل مع حاسوب محمول',
    nameEn: 'Office Workstation Desk',
    category: 'office_work',
    descriptionAr: 'مكتب عمل إداري، حاسوب محمول مستقر، كرسي مكتبي مريح مضغوط بوزن الجسم، وإضاءة سقفية منتظمة.',
    descriptionEn: 'Office desk with resting laptop, ergonomic chair compressed by body mass, professional overhead troffer LED light.',
    compatibleSceneTypes: ['desk_work_selfie', 'seated_selfie', 'close_face_selfie'],
    allowedPoses: ['seated_desk_workstation', 'seated_cushion_compression'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: true,
    hasContactSurface: true,
    allowedLighting: ['office_troffer_led', 'open_shade'],
    defaultActivity: 'sparse',
    environmentalElements: ['work desk laminate', 'laptop on desk', 'office pen holder', 'mesh ergonomic chair back'],
    saudiDetails: ['Saudi administrative office interior', 'discreet desk calendar or notebook with Arabic text'],
  },

  // Gym & Fitness
  {
    id: 'gym_workout_floor',
    nameAr: 'صالة الحديد والتمارين الرياضية',
    nameEn: 'Gym Fitness Workout Floor',
    category: 'gym_fitness',
    descriptionAr: 'أرضية مطاطية، أجهزة رياضية حقيقية في الخلفية، إضاءة صناعية بيضاء، وملابس رياضية عملية.',
    descriptionEn: 'Rubber mat gym floor, dumbbell racks and weight benches in background, bright overhead LED troffers.',
    compatibleSceneTypes: ['gym_workout_selfie', 'post_workout_selfie', 'standing_selfie', 'seated_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'gym_post_workout_recovery'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['retail_fluorescent_tubes', 'mixed_practical_ambient'],
    defaultActivity: 'light',
    environmentalElements: ['rubber flooring', 'distant dumbbell rack', 'workout bench', 'water shaker bottle'],
    saudiDetails: ['contemporary Saudi fitness center layout', 'athletic training sportswear suitable for indoor clubs'],
  },
  {
    id: 'gym_locker_mirror',
    nameAr: 'مرآة غرفة تبديل الملابس بالنادي',
    nameEn: 'Gym Locker Room Mirror',
    category: 'gym_fitness',
    descriptionAr: 'مرآة جدارية حقيقية، الهاتف ظاهر في اليد وموجه للمرآة، انعكاس متطابق بدقة هندسية.',
    descriptionEn: 'Wall-mounted locker room mirror, phone held visible in mirror reflection, strict optical reflection geometry.',
    compatibleSceneTypes: ['mirror_selfie', 'standing_selfie', 'post_workout_selfie'],
    allowedPoses: ['mirror_phone_held', 'gym_post_workout_recovery'],
    hasMirror: true,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['retail_fluorescent_tubes', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['framed mirror', 'wooden or metal locker doors in reflection', 'wash basin rim'],
    saudiDetails: ['clean luxury gym locker finishes', 'subtle gym locker numbering in Arabic/English'],
  },

  // Public Buildings & Elevators
  {
    id: 'building_elevator_mirror',
    nameAr: 'مرآة مصعد مبنى حديث',
    nameEn: 'Modern Building Elevator Mirror',
    category: 'public_buildings',
    descriptionAr: 'مرآة داخل كابينة المصعد من الفولاذ المقاوم للصدأ، إنارة سقفية موجهة، وانعكاس هاتف دقيق.',
    descriptionEn: 'Interior stainless steel elevator cabin with back-panel mirror, directional ceiling downlights, phone reflected in hand.',
    compatibleSceneTypes: ['mirror_selfie', 'standing_selfie'],
    allowedPoses: ['mirror_phone_held'],
    hasMirror: true,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['office_troffer_led', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['elevator handrail', 'brushed steel wall panels', 'ceiling LED spotlights', 'floor indicator panel'],
    saudiDetails: ['modern Saudi corporate or residential tower elevator specs', 'Arabic inspection plaque in corner'],
  },
  {
    id: 'public_building_hallway',
    nameAr: 'ممر وردهة مبنى عام',
    nameEn: 'Public Building Corridor / Hallway',
    category: 'public_buildings',
    descriptionAr: 'ممر مبلط ببلاط سيراميك أو رخام، أبواب مكاتب، إنارة متناسقة ومنظور هندسي متقارب.',
    descriptionEn: 'Symmetrical polished floor corridor, directional ceiling lights, architectural vanishing point, clean walls.',
    compatibleSceneTypes: ['walking_selfie', 'standing_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['office_troffer_led', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['polished stone floor', 'ceiling tile grid', 'emergency exit sign', 'office doors along hall'],
    saudiDetails: ['bilingual Arabic/English room numbers and exit signage'],
  },

  // Public Wash Areas & Mirrors
  {
    id: 'restaurant_washroom_mirror',
    nameAr: 'مرآة مغاسل مطعم راقي',
    nameEn: 'Restaurant Restroom Wash Mirror',
    category: 'wash_mirrors',
    descriptionAr: 'مرآة حائط فوق مغاسل رخامية، إضاءة جانبية أو خلفية للمرآة، الهاتف يظهر في اليد أمام المرآة.',
    descriptionEn: 'Vanity mirror above stone basin counter, ambient sconce lighting, camera reflection accurately oriented.',
    compatibleSceneTypes: ['mirror_selfie', 'standing_selfie'],
    allowedPoses: ['mirror_phone_held'],
    hasMirror: true,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['cafe_warm_practical_amber', 'mixed_practical_ambient'],
    defaultActivity: 'sparse',
    environmentalElements: ['marble countertop', 'modern chrome faucet', 'soap dispenser', 'mirror perimeter glow'],
    saudiDetails: ['clean luxury restaurant hospitality decor in Riyadh or Jeddah'],
  },

  // Shopping & Supermarket
  {
    id: 'supermarket_aisle',
    nameAr: 'ممر تموينات وسوبرماركت',
    nameEn: 'Supermarket Grocery Aisle',
    category: 'shopping',
    descriptionAr: 'ممر سوبرماركت حقيقي بين رفوف المنتجات، أرضية ملساء، سلة تسوق، وإنارة فلورسنت بيضاء.',
    descriptionEn: 'Real supermarket aisle with stocked product shelving, linoleum floor, shopping basket in hand, authentic retail lights.',
    compatibleSceneTypes: ['standing_selfie', 'walking_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer', 'holding_shopping_basket'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['retail_fluorescent_tubes'],
    defaultActivity: 'light',
    environmentalElements: ['stocked shelves with groceries', 'supermarket aisle floor', 'plastic shopping basket', 'price tags on shelf edge'],
    saudiDetails: ['authentic Gulf supermarket packaging (milk, tea, local goods)', 'Arabic price tags (SAR)'],
  },
  {
    id: 'mall_corridor',
    nameAr: 'ردهة وممشى المول التجاري',
    nameEn: 'Mall Main Walkway Corridor',
    category: 'shopping',
    descriptionAr: 'ردهة مول واسعة، واجهات محلات ملابس، أرضية رخامية لامعة، وحركة متسوقين طبيعية غير موجهة للكاميرا.',
    descriptionEn: 'Spacious retail mall atrium, storefront displays, polished marble flooring, unposed ambient shoppers in distance.',
    compatibleSceneTypes: ['walking_selfie', 'standing_selfie', 'wide_environmental_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['retail_fluorescent_tubes', 'mixed_practical_ambient', 'open_shade'],
    defaultActivity: 'moderate',
    environmentalElements: ['polished marble floor', 'glass railing balcony', 'storefront retail displays', 'bench seating'],
    saudiDetails: ['major Saudi mall atrium scale (e.g. Riyadh Park or Red Sea Mall style)', 'modest Saudi everyday shoppers in soft background'],
  },

  // Airport Terminal
  {
    id: 'airport_gate_waiting',
    nameAr: 'صالة انتظار بوابة المطار',
    nameEn: 'Airport Gate Waiting Area',
    category: 'airport',
    descriptionAr: 'مقاعد انتظار المسافرين، حقيبة سفر مرتكزة على الأرض بجانب القدم، نوافذ زجاجية تطل على ساحة الطائرات.',
    descriptionEn: 'Airport terminal gate seating, carry-on rolling luggage resting firmly on carpet/tile floor, tarmac glass window background.',
    compatibleSceneTypes: ['seated_selfie', 'standing_selfie', 'front_selfie'],
    allowedPoses: ['seated_cushion_compression', 'standing_asymmetric_weight', 'luggage_handle_interaction'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true,
    allowedLighting: ['open_shade', 'retail_fluorescent_tubes', 'mixed_practical_ambient'],
    defaultActivity: 'moderate',
    environmentalElements: ['metal terminal row seats', 'wheeled cabin luggage upright on floor', 'flight info display screen in distance', 'large apron windows'],
    saudiDetails: ['Saudi airport signage typography (Saudia / Flynas gate indicators)', 'bilingual departure gate signs'],
  },

  // Desert & Road Trips
  {
    id: 'desert_highway_stop',
    nameAr: 'استراحة على طريق صحراوي سريع',
    nameEn: 'Desert Highway Roadside Pullout',
    category: 'desert_roadtrips',
    descriptionAr: 'كتف طريق صحراوي واسع، أسفلت جاف، رمال ممتدة، سيارة دفع رباعي متوقفة، وأفق صحراوي مفتوح.',
    descriptionEn: 'Desert highway shoulder pullout, warm dry asphalt, natural sand embankment, parked SUV with heat shimmer.',
    compatibleSceneTypes: ['desert_stop_selfie', 'car_adjacent_selfie', 'standing_selfie', 'leaning_selfie', 'wide_environmental_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface', 'beside_car_open_door_clearance'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Vehicle
    allowedLighting: ['direct_sun', 'harsh_noon', 'golden_hour'],
    defaultActivity: 'sparse',
    environmentalElements: ['highway asphalt shoulder', 'desert sand dunes on horizon', 'parked vehicle', 'metal crash barrier in distance'],
    saudiDetails: ['classic Saudi intercity highway scenery (Riyadh-Qassim or Makkah road)', 'faint red/ochre desert sand texture'],
  },

  // Mountain Locations
  {
    id: 'mountain_scenic_viewpoint',
    nameAr: 'إطلالة جبلية ومنحدرات السودة/الشفا',
    nameEn: 'Mountain Ridge Roadside Viewpoint',
    category: 'mountain_locations',
    descriptionAr: 'منصة مراقبة صخرية أو استراحة على جبل، حافة صخرية آمنة، ضباب خفيف في الوديان، وإطلالة طبيعية.',
    descriptionEn: 'Rocky mountain overlook, paved scenic pullout, distant valley fog, natural rocky terrain contact under footwear.',
    compatibleSceneTypes: ['mountain_view_selfie', 'standing_selfie', 'leaning_selfie', 'wide_environmental_selfie', 'front_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'leaning_against_contact_surface'],
    hasMirror: false,
    hasCar: true,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: true, // Stone barrier
    allowedLighting: ['direct_sun', 'golden_hour', 'overcast_diffused'],
    defaultActivity: 'sparse',
    environmentalElements: ['natural rocky mountain ground', 'stone parapet wall', 'distant mountain ridge layers', 'cool mountain atmospheric haze'],
    saudiDetails: ['Sarawat mountain ridge aesthetics (Abha/Taif topography)', 'subtle juniper vegetation patches in distance'],
  },

  // Farms & Palm Areas
  {
    id: 'palm_oasis_path',
    nameAr: 'ممر مزرعة نخيل ريفية',
    nameEn: 'Rural Date Palm Farm Pathway',
    category: 'farms_palms',
    descriptionAr: 'طريق ترابي غير معبد بين جذوع النخيل، إضاءة شمس متخللة بين السعف، سياج طيني أو شبكي بسيط.',
    descriptionEn: 'Dirt agricultural path between towering date palms, dappled sunlight filtering through fronds, authentic rural atmosphere.',
    compatibleSceneTypes: ['farm_palm_selfie', 'walking_selfie', 'standing_selfie', 'wide_environmental_selfie'],
    allowedPoses: ['standing_asymmetric_weight', 'walking_mid_stride_weight_transfer'],
    hasMirror: false,
    hasCar: false,
    hasTable: false,
    hasDesk: false,
    hasContactSurface: false,
    allowedLighting: ['direct_sun', 'open_shade', 'golden_hour'],
    defaultActivity: 'sparse',
    environmentalElements: ['unpaved compacted soil road', 'date palm trunks', 'irrigation canal ditch', 'dry palm fronds'],
    saudiDetails: ['Al-Ahsa / Al-Qassim heritage farm landscape', 'authentic irrigation channels and date cluster silhouettes'],
  },
];

export const POSE_DEFINITIONS: Record<
  PoseType,
  {
    nameAr: string;
    nameEn: string;
    biomechanicsDescAr: string;
    biomechanicsDescEn: string;
    requiresSupport: boolean;
    requiresContact: boolean;
    requiresMirror: boolean;
  }
> = {
  standing_asymmetric_weight: {
    nameAr: 'وقوف مع ارتكاز وزن غير متناظر (طبيعي)',
    nameEn: 'Standing (Asymmetric Weight Distribution)',
    biomechanicsDescAr: 'ارتكاز مركز الثقل على ساق واحدة مع استرخاء الأخرى، انحناء طبيعي بسيط في الحوض، كتف اليد الحاملة للهاتف مرتفع قليلاً.',
    biomechanicsDescEn: 'Center of mass primarily supported by dominant leg, relaxed contrapposto pelvic tilt, camera-arm shoulder slightly elevated.',
    requiresSupport: false,
    requiresContact: false,
    requiresMirror: false,
  },
  walking_mid_stride_weight_transfer: {
    nameAr: 'مشية حقيقية في منتصف الخطوة (نقل الوزن)',
    nameEn: 'Walking (Mid-Stride Dynamic Weight Transfer)',
    biomechanicsDescAr: 'خطوة غير متماثلة: كعب القدم الأمامية يلامس الأرض بينما ترتفع أصابع القدم الخلفية، حركة تأرجح خفيفة للذراع الحرة، تثبيت اليد الحاملة للهاتف.',
    biomechanicsDescEn: 'Asymmetric stride: front heel strike with trailing foot toe-off, subtle natural free-arm swing, plausible handheld stabilization.',
    requiresSupport: false,
    requiresContact: false,
    requiresMirror: false,
  },
  seated_cushion_compression: {
    nameAr: 'جلوس مستقر مع انضغاط وسادة المقعد',
    nameEn: 'Seated (Natural Seat Cushion Compression)',
    biomechanicsDescAr: 'الحوض مدعوم بالكامل بسطح المقعد، انضغاط في حشوة الكرسي بوزن الجسم، الفخذان مستويان، القدمان متطابقتان مع ارتفاع الكرسي.',
    biomechanicsDescEn: 'Pelvis fully anchored on support plane, visible seat cushion compression from body mass, thighs aligned with seat level, feet grounded.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  seated_desk_workstation: {
    nameAr: 'جلوس عند مكتب عمل مع ذراع مستندة',
    nameEn: 'Seated at Office Desk (Forearm Grounded)',
    biomechanicsDescAr: 'الساعد أو الكوع مستند على سطح المكتب الصلب، الشاشة والأغراض على المكتب ثابتة، وضعية جلوس مكتبية مريحة.',
    biomechanicsDescEn: 'Forearm lightly resting on desk surface, laptop/papers resting flat, relaxed seated posture with lumbar support.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  leaning_against_contact_surface: {
    nameAr: 'استناد جسدي على سطح داعم (جدار/سيارة/درابزين)',
    nameEn: 'Leaning Against Real Contact Surface',
    biomechanicsDescAr: 'إزاحة مركز الثقل باتجاه سطح التلامس (جدار، هيكل سيارة، أو درابزين)، نقطة تلامس فيزيائية واضحة للكتف أو الحوض، زاوية انحناء طبيعية.',
    biomechanicsDescEn: 'Center of gravity shifted toward support surface (wall, car body, railing), definitive physical contact at shoulder/hip, biomechanically plausible tilt.',
    requiresSupport: false,
    requiresContact: true,
    requiresMirror: false,
  },
  seated_table_casual: {
    nameAr: 'جلوس حول طاولة طعام/مقهى',
    nameEn: 'Seated at Dining/Cafe Table',
    biomechanicsDescAr: 'اليد الحرة أو المعصم مستقر على حافة الطاولة، الأكواب والأطباق ترتكز فعلياً على السطح دون اختراق، مسافة واقعية بين الجسم والكرسي.',
    biomechanicsDescEn: 'Free hand resting on table plane, beverage cups firmly grounded on continuous surface, natural clearance between chair and table edge.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  holding_cup_table: {
    nameAr: 'إمساك كوب قهوة مرتكز على الطاولة',
    nameEn: 'Holding Coffee Cup on Table Surface',
    biomechanicsDescAr: 'الأصابع ملتفة حول الكوب الخزفي، قاعدة الكوب تلامس سطح الطاولة الخشبي، اليد الأخرى تحمل الهاتف على مسافة ذراع.',
    biomechanicsDescEn: 'Fingers contoured around ceramic mug base touching table surface, phone held at ergonomic half-arm extension.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  gym_post_workout_recovery: {
    nameAr: 'استراحة بعد التمرين (تعرق خفيف وإرهاق طبيعي)',
    nameEn: 'Post-Workout Standing / Recovery',
    biomechanicsDescAr: 'وقوف مسترخٍ بعد الجهد البدني، تعرق خفيف غير لامع على الجبهة والرقبة، تورد طبيعي خفيف للبشرة، استرخاء عضلات الكتف.',
    biomechanicsDescEn: 'Relaxed athletic stance post-exertion, subtle realistic perspiration across brow/neck, light flushed complexion, natural workout clothing drape.',
    requiresSupport: false,
    requiresContact: false,
    requiresMirror: false,
  },
  mirror_phone_held: {
    nameAr: 'إمساك الهاتف أمام المرآة (مرئي في الانعكاس)',
    nameEn: 'Holding Phone in Front of Mirror',
    biomechanicsDescAr: 'الهاتف ظاهر في اليد وموجه للمرآة، العينان تنظران لشاشة الهاتف أو للمرآة، الانعكاس يتطابق هندسياً مع موضع الكاميرا والجسم.',
    biomechanicsDescEn: 'Smartphone visibly held in hand aimed at mirror surface, gaze directed at phone screen or mirror reflection, strict ray-traced reflection geometry.',
    requiresSupport: false,
    requiresContact: false,
    requiresMirror: true,
  },
  inside_car_driver_one_hand_wheel: {
    nameAr: 'يد واحدة على المقود واليد الأخرى تحمل الهاتف',
    nameEn: 'Inside Car: One Hand on Steering Wheel',
    biomechanicsDescAr: 'اليد اليسرى ممسكة بإطار المقود (السيارة متوقفة)، اليد اليمنى تحمل الهاتف ضمن أبعاد مقصورة السيارة، زاوية الزجاج الجانبي مرئية.',
    biomechanicsDescEn: 'One hand resting on steering wheel rim in stationary parked car, other arm holding phone within cabin reach limit, authentic windscreen parallax.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  inside_car_passenger_armrest: {
    nameAr: 'جلوس في مقعد الراكب مستنداً على مسند الذراع',
    nameEn: 'Inside Car: Passenger with Armrest Lean',
    biomechanicsDescAr: 'المرفق مستند على مسند الذراع الأوسط، زاوية الكاميرا تستعرض مساحة كابينة الركاب والزجاج الجانبي الأيمن.',
    biomechanicsDescEn: 'Elbow resting on center console, phone elevated slightly within passenger seat envelope, side glass illumination.',
    requiresSupport: true,
    requiresContact: true,
    requiresMirror: false,
  },
  beside_car_open_door_clearance: {
    nameAr: 'وقوف بجانب باب السيارة المفتوح (مساحة كافية)',
    nameEn: 'Beside Car with Open Door Clearance',
    biomechanicsDescAr: 'باب السيارة مفتوح بزاوية هندسية معقولة، الشخص يقف في المساحة الخالية بين الباب والهيكل دون تداخل أو اختراق للمعادن.',
    biomechanicsDescEn: 'Car door open at plausible geometric angle, subject standing in clear spatial pocket without body penetration of metal panels.',
    requiresSupport: false,
    requiresContact: false,
    requiresMirror: false,
  },
  luggage_handle_interaction: {
    nameAr: 'إمساك مقبض حقيبة السفر المرتكزة بالأرض',
    nameEn: 'Hand Resting on Upright Luggage Handle',
    biomechanicsDescAr: 'حقيبة السفر مرتكزة على عجلاتها على أرضية الصالة، الذراع ممدودة برفق لمسك المقبض التلسكوبي، حقيبة الظهر أو المعطف طبيعي.',
    biomechanicsDescEn: 'Wheeled luggage planted firmly on floor tiles, hand resting naturally on extended telescopic handle, relaxed transit posture.',
    requiresSupport: false,
    requiresContact: true,
    requiresMirror: false,
  },
  holding_shopping_basket: {
    nameAr: 'حمل سلة تسوق باليد في الممر',
    nameEn: 'Holding Grocery Shopping Basket',
    biomechanicsDescAr: 'سلة التسوق البلاستيكية تتدلى من يد واحدة بثقل معقول، الجسم يقف أو يمشي بمحاذاة الرفوف دون لمس البضائع المعروضة.',
    biomechanicsDescEn: 'Shopping basket held naturally in one hand with realistic arm tension from basket mass, stance aligned parallel to shelving.',
    requiresSupport: false,
    requiresContact: true,
    requiresMirror: false,
  },
};

export const SAUDI_REALISM_DETAILS = [
  'Yellow and black checker painted curbs along municipal sidewalk edge',
  'Authentic Gulf-specification daily commuter vehicles (Toyota Land Cruiser, Camry, Nissan Patrol)',
  'Bilingual Arabic-English street and commercial signs with standard Saudi font proportions',
  'Fine desert dust patina settled in deep wheel rims and windshield corners',
  'Subtle modern Saudi architectural elements: light sandstone villa boundary walls, practical recessed windows',
  'Practical public infrastructure: municipal waste bins, shaded parking fabric canopies, decorative cast metal street poles',
  'Natural everyday clothing: crisp white or dark tailored thobe with casual shemagh, or contemporary neat casual streetwear',
  'Harsh atmospheric high-sunlight contrast and authentic Gulf coastal humidity or dry desert clarity',
];

export const IMPERFECTION_LAYER_ELEMENTS = [
  'Minor asphalt patches with slightly varied asphalt bitumen texture',
  'Faded street lane markings and slightly scuffed curb concrete',
  'Natural dust accumulation in crevices and non-contact vehicle surfaces',
  'Slightly uneven placement of casual objects (keys, beverage cup, napkins)',
  'Ordinary smartphone camera optical lens flare and subtle single-lens barrel distortion',
  'Subtle natural skin texture (vellus hair rim glow, non-uniform natural sebum, visible dermatological pores)',
  'Micro-crease fabric tension in clothing responding to body movement and gravity (g=9.8 m/s²)',
  'Faint fingerprint smudge or micro-glare on mirror edges in mirror selfies',
];

export const DEFAULT_SELFIE_STATE: SelfieSceneState = {
  sceneType: 'front_selfie',
  locationCategory: 'city_streets',
  locationId: 'residential_street',
  pose: 'standing_asymmetric_weight',
  cameraPosition: 'handheld_arm_extended_front',
  cameraAngle: 'eye_level',
  framing: 'head_and_shoulders',
  lighting: 'open_shade',
  timeOfDay: 'late_afternoon',
  weather: 'clear_dry',
  backgroundActivity: 'sparse',
  environmentalObjects: ['curb line', 'parked car in distance', 'residential wall'],
  clothingType: 'casual everyday attire (clean white Saudi thobe or neat casual shirt)',
  includeSaudiRealism: true,
  includeImperfectionLayer: true,
  customNotes: '',
};
